#!/bin/bash
set -eu

cd "$(dirname "$0")"

# --no-input seems to work well
# but if need more targeted approach, pparently can mark certain cells with tag and use '--TagRemovePreprocessor.remove_cell_tags={"noexport"}' ?
exec uvx --with jupyter --from jupyter-core jupyter nbconvert --execute --to markdown --no-input README.ipynb

# TODO run it on CI to make sure it renders and up to date?
