services:
  redis:
    image: "redis:alpine"
    # restart: always
    command:
      - "sh"
      - "-euc"
      - |
        exec redis-server
      # - |
      #   echo "requirepass '$$REDIS_PASSWORD'" > /etc/redis.conf
      #   exec redis-server /etc/redis.conf
    # environment:
    #   REDIS_PASSWORD: "password"
    ports:
      - 6379:6379
    volumes:
      - "redis-cachew:/data:rw"

volumes:
  redis-cachew:
